---
- name: configure docker repo
  template: src=docker.repo
            dest=/etc/yum.repos.d/docker.repo

- name: install registry dependencies
  yum: name="{{ item }}" enablerepo=dockerrepo state=present
  with_items:
    - docker-engine

- name: start docker service
  service: name=docker state=started enabled=yes

- name: create registry cert dir
  file: path="{{ ca_cert_path }}" state=directory mode=0755

- name: install registry ca.crt
  copy: src="{{ playbook_dir }}/files/ca.pem" dest="{{ ca_cert_path }}/ca.crt"
  notify:
    - restart docker

- name: create registry directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
    - /var/lib/registry/data
    - /var/lib/registry/certs

- name: copy TLS files
  copy: src="{{ playbook_dir }}/files/{{ item }}" dest="/var/lib/registry/certs/{{ item }}"
  with_items:
    - ca.pem
    - registry.pem
    - registry_key.pem

- name: set registry key security
  file: path=/var/lib/registry/certs/registry_key.pem mode=0600

- name: install pip
  easy_install: name=pip state=latest

- name: install docker-py
  pip: name=docker-py

- name: create registry container
  docker:
    name: registry
    image: registry:2
    state: reloaded
    restart_policy: on-failure
    ports:
      - "5000:5000"
    volumes:
      - "/var/lib/registry/data:/var/lib/registry"
      - "/var/lib/registry/certs:/certs"
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.pem
      REGISTRY_HTTP_TLS_KEY: /certs/registry_key.pem