---
- name: configure docker repo
  template: src=docker.repo
            dest=/etc/yum.repos.d/docker.repo

- name: install shell dependencies
  yum: name="{{ item }}" enablerepo=dockerrepo state=present
  with_items:
    - docker-engine

- name: create doctl dir
  file: path=/opt/doctl state=directory mode=0755

- name: fetch doctl
  get_url: url="{{ doctl_url }}" dest=/tmp/doctl.tar.gz

- name: unarchive doctl
  unarchive: src=/tmp/doctl.tar.gz dest=/opt/doctl copy=no

- name: remove download archive
  file: path=/tmp/doctl.tar.gz state=absent

- name: symlink doctl
  file: src=/opt/doctl/doctl dest=/usr/local/bin/doctl state=link

- name: create doctl config for centos user
  template: src=doctlcfg dest=/home/centos/.doctlcfg mode=0600 owner=centos